spring:
  application:
    name: bookclub

  logging:
    level:
      org.springframework.security: DEBUG

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jwt:
    secret: ${JWT_SECRET_KEY}
    expiration-ms: 86400000

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_schema: bookclub
        format_sql: true
    show-sql: true
